"""add img field

Revision ID: 4acdfa2fbbea
Revises: 64358bf14a4b
Create Date: 2025-01-01 17:50:55.786056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acdfa2fbbea'
down_revision: Union[str, None] = '64358bf14a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'img')
    # ### end Alembic commands ###
